In [2]:
import numpy as np

# Problem 2
## Part a)

In [5]:
A1 = np.random.randn(1, 1)
A2 = np.random.randn(2, 2)
A3 = np.random.randn(3, 3)

z1 = np.zeros((1, 1))
z2 = np.zeros((2, 2))
z3 = np.zeros((3, 3))

B1 = np.block([[z1, A1], [A1, z1]])
B2 = np.block([[z2, A2], [A2, z2]])
B3 = np.block([[z3, A3], [A3, z3]])

A1_eigs = np.linalg.eig(A1)
B1_eigs = np.linalg.eig(B1)

A2_eigs = np.linalg.eig(A2)
B2_eigs = np.linalg.eig(B2)

A3_eigs = np.linalg.eig(A3)
B3_eigs = np.linalg.eig(B3)

print("The eigenvalue and eigenvector of A (1x1) is:\n" + str(A1_eigs) + "\nThe eigenvalues and eigenvectors of B (2x2) are:\n"
        + str(B1_eigs) + "\nThe eigenvalues and eigenvectors of A (2x2) are:\n" + str(A2_eigs) + "\nThe eigenvalues and eigenvectors of B "
        "(4x4) are:\n" + str(B2_eigs) + "\nThe eigenvalues and eigenvectors of A (3x3) are:\n" + str(A3_eigs) + "\nThe eigenvalues and "
        "eigenvectors of B (6x6) are:\n" + str(B3_eigs))

The eigenvalue and eigenvector of A (1x1) is:
(array([-0.76143029]), array([[1.]]))
The eigenvalues and eigenvectors of B (2x2) are:
(array([ 0.76143029, -0.76143029]), array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]]))
The eigenvalues and eigenvectors of A (2x2) are:
(array([ 0.23229651, -0.35075968]), array([[ 0.74239953,  0.74217322],
       [-0.66995741,  0.67020811]]))
The eigenvalues and eigenvectors of B (4x4) are:
(array([ 0.35075968,  0.23229651, -0.35075968, -0.23229651]), array([[-0.52479571, -0.52495574,  0.52479571,  0.52495574],
       [-0.4739087 ,  0.47373143,  0.4739087 , -0.47373143],
       [ 0.52479571, -0.52495574,  0.52479571, -0.52495574],
       [ 0.4739087 ,  0.47373143,  0.4739087 ,  0.47373143]]))
The eigenvalues and eigenvectors of A (3x3) are:
(array([-1.19394782, -0.38569422,  1.58342888]), array([[-0.48474804, -0.92444763, -0.84311408],
       [-0.20202936, -0.11434363, -0.52383894],
       [-0.85100145, -0.36376107,  0.1214554 ]]))
T

### So, we can see that the eigenvalues are generally just the same as the eigenvalues for A or they are negative permutations of the eigenvalues of A. The eigenvectors are related by a factor of square root of 2.

# Problem 3
## Part a)
### Using the power method, we find the eigenvalues, eigenvectors, determinant, and nonsingular matrix U such that U^(-1)AU is a diagonal matrix.

In [50]:
A = np.array([[0, -3, -2], [2, 5, 2], [-2, -3, 0]])
A

array([[ 0, -3, -2],
       [ 2,  5,  2],
       [-2, -3,  0]])

### Using the power method, we obtain the following.

In [51]:
def power_method(A, nsim):
    v_k = np.random.rand(A.shape[0])

    for i in range(nsim):
        v_k = np.matmul(A, v_k)
        v_k /= np.linalg.norm(v_k)

    return v_k

nsim = 100000
v_1 = power_method(A, nsim)

check = np.divide(A@v_1, v_1)
lambda_1 = check[0]
print("We have that the principal eigenvector of A is\n" + str(v_1) + "\nFrom this we also obtain the principal eigenvalue which is: "
        + str(lambda_1))

We have that the principal eigenvector of A is
[-0.56792422  0.68391709 -0.45795141]
From this we also obtain the principal eigenvalue which is: 2.0


### Now, using built-in functions, we find the eigenvalues, eigenvectors, determinant, and nonsingular matrix U such that U^(-1)AU is a diagonal matrix.

In [16]:
A_eigs = np.linalg.eig(A)
A_det = np.linalg.det(A)

U = A_eigs[1]
Uinv = np.linalg.inv(U)
D = Uinv@B@U

print("The eigenvalues and eigenvectors of A are:\n" + str(A_eigs) + "\nThe determinant of A is: " + str(A_det) + ", and a nonsingular "
        "matrix U such that U^(-1)AU is a diagonal matrix is:\n" + str(U) + "\nwhere D=U^(-1)AU is given by:\n" + str(D))

The eigenvalues and eigenvectors of A are:
(array([1., 2., 2.]), array([[-0.57735027, -0.33333333,  0.19088005],
       [ 0.57735027,  0.66666667, -0.62942278],
       [-0.57735027, -0.66666667,  0.75325412]]))
The determinant of A is: 4.000000000000001, and a nonsingular matrix U such that U^(-1)AU is a diagonal matrix is:
[[-0.57735027 -0.33333333  0.19088005]
 [ 0.57735027  0.66666667 -0.62942278]
 [-0.57735027 -0.66666667  0.75325412]]
where D=U^(-1)AU is given by:
[[ 1.00000000e+00  1.33226763e-15 -8.88178420e-16]
 [-7.10542736e-15  2.00000000e+00  7.10542736e-15]
 [-1.77635684e-15 -1.77635684e-15  2.00000000e+00]]


# Problem 4
## Part a)

In [16]:
np.random.seed(1)

n = 100
A = np.random.rand(n, n)
A = np.diag(np.diag(A)) + np.triu(A, 1) + np.triu(A, 1).T
A

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, ...,
        5.73679487e-01, 2.87032703e-03, 6.17144914e-01],
       [7.20324493e-01, 5.27058102e-01, 8.85942099e-01, ...,
        2.34362086e-01, 6.16778357e-01, 9.49016321e-01],
       [1.14374817e-04, 8.85942099e-01, 9.15606350e-01, ...,
        7.96260777e-02, 9.82817114e-01, 1.81612851e-01],
       ...,
       [5.73679487e-01, 2.34362086e-01, 7.96260777e-02, ...,
        8.35276181e-01, 2.39285522e-01, 7.30797255e-02],
       [2.87032703e-03, 6.16778357e-01, 9.82817114e-01, ...,
        2.39285522e-01, 5.08370915e-01, 8.47333803e-02],
       [6.17144914e-01, 9.49016321e-01, 1.81612851e-01, ...,
        7.30797255e-02, 8.47333803e-02, 7.62793778e-01]])

In [17]:
def power_method(A, nsim):
    v_k = np.random.rand(A.shape[0])

    for i in range(nsim):
        v_k = np.matmul(A, v_k)
        v_k /= np.linalg.norm(v_k)

    return v_k

nsim = 100000
v_1 = power_method(A, nsim)
v_1

array([0.09608098, 0.09734805, 0.10836906, 0.09888139, 0.09845307,
       0.09585422, 0.09690958, 0.10429969, 0.09501   , 0.09526097,
       0.09927609, 0.10038285, 0.09724628, 0.10525882, 0.0919113 ,
       0.10260968, 0.10659609, 0.10893956, 0.10713686, 0.10291671,
       0.08912949, 0.09238826, 0.10528212, 0.09453652, 0.09259544,
       0.08567914, 0.09954917, 0.09323791, 0.09860583, 0.09782563,
       0.10184378, 0.09818615, 0.10079504, 0.09666537, 0.10472988,
       0.0915029 , 0.09810982, 0.1002086 , 0.11160975, 0.09732125,
       0.10156742, 0.09885113, 0.09927934, 0.10389348, 0.08616502,
       0.10717184, 0.10064086, 0.11278075, 0.09723566, 0.10842254,
       0.08831443, 0.11586237, 0.09468799, 0.09321103, 0.10931931,
       0.09480007, 0.10010469, 0.09930226, 0.10920202, 0.10496486,
       0.09984006, 0.10349324, 0.09267888, 0.10147076, 0.09599864,
       0.08991323, 0.09908404, 0.10214758, 0.1031716 , 0.08713201,
       0.10043127, 0.09606944, 0.09829078, 0.09935098, 0.09194

### To check if this is a valid eigenvector, we compute the element-wise division of Av and v and if it works, we will obtain a matrix of the principal eigenvalue.

In [18]:
check = np.divide(A@v_1, v_1)
lambda_1 = check[0]
print(check)
print("From this we also obtain the principal eigenvalue which is just the value shown below, i.e, " + str(lambda_1))

[50.58089568 50.58089568 50.58089568 50.58089568 50.58089568 50.58089568
 50.58089568 50.58089568 50.58089568 50.58089568 50.58089568 50.58089568
 50.58089568 50.58089568 50.58089568 50.58089568 50.58089568 50.58089568
 50.58089568 50.58089568 50.58089568 50.58089568 50.58089568 50.58089568
 50.58089568 50.58089568 50.58089568 50.58089568 50.58089568 50.58089568
 50.58089568 50.58089568 50.58089568 50.58089568 50.58089568 50.58089568
 50.58089568 50.58089568 50.58089568 50.58089568 50.58089568 50.58089568
 50.58089568 50.58089568 50.58089568 50.58089568 50.58089568 50.58089568
 50.58089568 50.58089568 50.58089568 50.58089568 50.58089568 50.58089568
 50.58089568 50.58089568 50.58089568 50.58089568 50.58089568 50.58089568
 50.58089568 50.58089568 50.58089568 50.58089568 50.58089568 50.58089568
 50.58089568 50.58089568 50.58089568 50.58089568 50.58089568 50.58089568
 50.58089568 50.58089568 50.58089568 50.58089568 50.58089568 50.58089568
 50.58089568 50.58089568 50.58089568 50.58089568 50

## Part b)

In [19]:
nsim = 100000

v_k = np.random.rand(A.shape[0])
for i in range(nsim):
    v_k = np.linalg.solve(A, v_k)
    v_k /= np.linalg.norm(v_k)

check = np.divide(A@v_k, v_k)
lambda_k = check[0]
print(check)
print("From this we also obtain the principal eigenvalue which is just the value shown below, i.e, " + str(lambda_k))

[0.01640417 0.01640417 0.01640417 0.01640417 0.01640417 0.01640417
 0.01640417 0.01640417 0.01640417 0.01640417 0.01640417 0.01640417
 0.01640417 0.01640417 0.01640417 0.01640417 0.01640417 0.01640417
 0.01640417 0.01640417 0.01640417 0.01640417 0.01640417 0.01640417
 0.01640417 0.01640417 0.01640417 0.01640417 0.01640417 0.01640417
 0.01640417 0.01640417 0.01640417 0.01640417 0.01640417 0.01640417
 0.01640417 0.01640417 0.01640417 0.01640417 0.01640417 0.01640417
 0.01640417 0.01640417 0.01640417 0.01640417 0.01640417 0.01640417
 0.01640417 0.01640417 0.01640417 0.01640417 0.01640417 0.01640417
 0.01640417 0.01640417 0.01640417 0.01640417 0.01640417 0.01640417
 0.01640417 0.01640417 0.01640417 0.01640417 0.01640417 0.01640417
 0.01640417 0.01640417 0.01640417 0.01640417 0.01640417 0.01640417
 0.01640417 0.01640417 0.01640417 0.01640417 0.01640417 0.01640417
 0.01640417 0.01640417 0.01640417 0.01640417 0.01640417 0.01640417
 0.01640417 0.01640417 0.01640417 0.01640417 0.01640417 0.0164

## Part c)

In [25]:
nsim = 100000

v_k2 = np.random.rand(A.shape[0])
v_k2 = v_k2 - np.matmul(v_k, v_k2)*v_k
for i in range(nsim):
    v_k2 = np.linalg.solve(A, v_k2)
    v_k2 = v_k2 - np.matmul(v_k, v_k2)*v_k
    v_k2 /= np.linalg.norm(v_k2)

check = np.divide(A@v_k2, v_k2)
lambda_k2 = check[0]
print(check)
print("From this we also obtain the principal eigenvalue which is just the value shown below, i.e, " + str(lambda_k2))

[-0.0613411 -0.0613411 -0.0613411 -0.0613411 -0.0613411 -0.0613411
 -0.0613411 -0.0613411 -0.0613411 -0.0613411 -0.0613411 -0.0613411
 -0.0613411 -0.0613411 -0.0613411 -0.0613411 -0.0613411 -0.0613411
 -0.0613411 -0.0613411 -0.0613411 -0.0613411 -0.0613411 -0.0613411
 -0.0613411 -0.0613411 -0.0613411 -0.0613411 -0.0613411 -0.0613411
 -0.0613411 -0.0613411 -0.0613411 -0.0613411 -0.0613411 -0.0613411
 -0.0613411 -0.0613411 -0.0613411 -0.0613411 -0.0613411 -0.0613411
 -0.0613411 -0.0613411 -0.0613411 -0.0613411 -0.0613411 -0.0613411
 -0.0613411 -0.0613411 -0.0613411 -0.0613411 -0.0613411 -0.0613411
 -0.0613411 -0.0613411 -0.0613411 -0.0613411 -0.0613411 -0.0613411
 -0.0613411 -0.0613411 -0.0613411 -0.0613411 -0.0613411 -0.0613411
 -0.0613411 -0.0613411 -0.0613411 -0.0613411 -0.0613411 -0.0613411
 -0.0613411 -0.0613411 -0.0613411 -0.0613411 -0.0613411 -0.0613411
 -0.0613411 -0.0613411 -0.0613411 -0.0613411 -0.0613411 -0.0613411
 -0.0613411 -0.0613411 -0.0613411 -0.0613411 -0.0613411 -0.061

In [27]:
nsim = 100000

v_k3 = np.random.rand(A.shape[0])
v_k3 = v_k3 - np.dot(v_k, v_k3)*v_k - np.dot(v_k2, v_k3)*v_k2
for i in range(nsim):
    v_k3 = np.linalg.solve(A, v_k3)
    v_k3 = v_k3 - np.dot(v_k, v_k3)*v_k - np.dot(v_k2, v_k3)*v_k2
    v_k3 /= np.linalg.norm(v_k3)

check = np.divide(A@v_k3, v_k3)
lambda_k3 = check[0]
print(check)
print("From this we also obtain the principal eigenvalue which is just the value shown below, i.e, " + str(lambda_k3))

[0.12601275 0.12601275 0.12601275 0.12601275 0.12601275 0.12601275
 0.12601275 0.12601275 0.12601275 0.12601275 0.12601275 0.12601275
 0.12601275 0.12601275 0.12601275 0.12601275 0.12601275 0.12601275
 0.12601275 0.12601275 0.12601275 0.12601275 0.12601275 0.12601275
 0.12601275 0.12601275 0.12601275 0.12601275 0.12601275 0.12601275
 0.12601275 0.12601275 0.12601275 0.12601275 0.12601275 0.12601275
 0.12601275 0.12601275 0.12601275 0.12601275 0.12601275 0.12601275
 0.12601275 0.12601275 0.12601275 0.12601275 0.12601275 0.12601275
 0.12601275 0.12601275 0.12601275 0.12601275 0.12601275 0.12601275
 0.12601275 0.12601275 0.12601275 0.12601275 0.12601275 0.12601275
 0.12601275 0.12601275 0.12601275 0.12601275 0.12601275 0.12601275
 0.12601275 0.12601275 0.12601275 0.12601275 0.12601275 0.12601275
 0.12601275 0.12601275 0.12601275 0.12601275 0.12601275 0.12601275
 0.12601275 0.12601275 0.12601275 0.12601275 0.12601275 0.12601275
 0.12601275 0.12601275 0.12601275 0.12601275 0.12601275 0.1260

In [11]:
np.sort(np.abs(np.linalg.eig(A)[0]))

array([1.64041731e-02, 6.13410980e-02, 1.26012753e-01, 1.54523192e-01,
       2.31050909e-01, 2.66825338e-01, 3.35912531e-01, 3.75651040e-01,
       3.94365702e-01, 4.60087992e-01, 5.14258067e-01, 5.65548872e-01,
       5.76227158e-01, 5.94547082e-01, 6.86035099e-01, 7.53019281e-01,
       8.01048459e-01, 8.33310806e-01, 8.48844470e-01, 9.09477718e-01,
       9.67727382e-01, 1.00815960e+00, 1.01122041e+00, 1.06269523e+00,
       1.07426941e+00, 1.14028634e+00, 1.20832859e+00, 1.22267912e+00,
       1.26712010e+00, 1.29030491e+00, 1.32197611e+00, 1.36483161e+00,
       1.41598719e+00, 1.52913378e+00, 1.59167257e+00, 1.61895138e+00,
       1.62356438e+00, 1.66375533e+00, 1.68655212e+00, 1.69215343e+00,
       1.81241131e+00, 1.86540909e+00, 1.89782469e+00, 1.95234060e+00,
       1.95463761e+00, 2.01593473e+00, 2.14356165e+00, 2.17508446e+00,
       2.27182272e+00, 2.32935460e+00, 2.34720851e+00, 2.39190935e+00,
       2.41689426e+00, 2.56281184e+00, 2.56582331e+00, 2.59110976e+00,
      