In [7]:
import numpy as np
from scipy.integrate import quad

# Problem 3

## Part a)

### Below, I have implemented the function for polynomial dot product with integration as the inner product definition. To test the function, I have used the polynomials 1+2x and 3+4x which achieves the desired result.

In [8]:
def _multiply_vec_poly(v1, v2):
    res = np.zeros(np.size(v1)*np.size(v2))
    for exp1, i in enumerate(v1):
        for exp2, j in enumerate(v2):
            res[exp1+exp2] += i*j
    return res

def _vec_to_polynomial(x, v):
    res = 0
    for exp, i in enumerate(v):
        res += i*(x**exp)
    
    return res

def polynomialdot(f, g, tol=0.0001):
    prod = _multiply_vec_poly(f, g)

    res = quad(_vec_to_polynomial, 0, 1, args=(prod,))[0]
    if abs(res-round(res)) <= tol:
        return round(res)
    else:
        return res

f = np.array([1, 2, 0, 0])
g = np.array([3, 4, 0, 0])

res = polynomialdot(f, g)
res

10.666666666666666

## Part b)

### To check if the polynomials given form an orthonormal basis, I computed the polynomial dot product between each polynomial (in vector format) thus getting a 4x4 matrix that shows that polynomial dot product between a polynomial and itself yields 1 and between any two non-equal polynomials yields 0 thus showing orthonormality.

In [9]:
v = np.zeros((4, 4))

v[0] = np.array([1, 0, 0, 0])
v[1] = np.sqrt(3)*np.array([-1, 2, 0, 0])
v[2] = np.sqrt(5)*np.array([1, -6, 6, 0])
v[3] = np.sqrt(7)*np.array([-1, 12, -30, 20])

dot_matrix = np.zeros((4, 4))

for i in range(4):
    for j in range(4):
        dot_matrix[i, j] = polynomialdot(v[i], v[j])

dot_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Part c)

### Here I implement a gram schmidt function using the polynomial inner product and verify that it works for two example polynomials. I then verify again with a randomly generated polynomial of degree at most 10 and show that it produces an orthonormal set of vectors, in a similar way to the previous part, as desired.

In [10]:
def gram_schmidt(vec, tol=0.0001):
    e = np.zeros((np.shape(vec)))
    u = np.zeros((np.shape(vec)))

    for i, v in enumerate(vec):
        if i == 0:
            u[0] = v
            e[0] = u[0]/np.sqrt(polynomialdot(u[0], u[0], tol))
        else:
            u[i] = v
            for j in range(i):
                u[i] -= (polynomialdot(u[j], v, tol)/polynomialdot(u[j], u[j], tol))*u[j]
            e[i] = u[i]/np.sqrt(polynomialdot(u[i], u[i], tol))

    return e

f = np.array([1, 2, 0, 0])
g = np.array([3, 4, 0, 0])

vec = np.array([f, g])

res = gram_schmidt(vec)
res

array([[ 0.48038446,  0.96076892,  0.        ,  0.        ],
       [ 1.94145069, -3.32820118,  0.        ,  0.        ]])

In [17]:
vec = np.random.randint(-5, 5, (11, 11))
res = gram_schmidt(vec, tol=1e-40)

dot_matrix = np.zeros((11, 11))

for i in range(11):
    for j in range(11):
        dot_matrix[i, j] = polynomialdot(res[i], res[j])

print("##### Answer #####")
print("Below is the first four of the resulting orthonormal set of polynomials for the randomly generated set of vectors of degree at most 10.")
print(res[:4,:4])
print("Below is the first four of the resulting dot product matrix for the randomly generated set of vectors of degree at most 10.")
print(dot_matrix[:4,:4])

<ipython-input-8-6dc66c7d839f>:18: IntegrationWarning: The occurrence of roundoff error is detected, which prevents 
  the requested tolerance from being achieved.  The error may be 
  underestimated.
  res = quad(_vec_to_polynomial, 0, 1, args=(prod,))[0]
<ipython-input-8-6dc66c7d839f>:18: IntegrationWarning: The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.
  res = quad(_vec_to_polynomial, 0, 1, args=(prod,))[0]


##### Answer #####
Below is the first four of the resulting orthonormal set of polynomials for the randomly generated set of vectors of degree at most 10.
[[ -1.59581014   2.39371521   0.79790507   1.59581014]
 [  1.16042781  -0.83059097   0.32983684   0.25520668]
 [  0.3150773   -7.53411229  17.94511551   3.9709257 ]
 [ -3.37785274  31.52156275 -56.39452079   3.88464851]]
Below is the first four of the resulting dot product matrix for the randomly generated set of vectors of degree at most 10.
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Extra

### Below, I generate a random polynomial of degree at most 40 and as can be seen, my gram-schmidt function does not work for polynomials of this size. It does not work because for larger and larger polynomials, numerical integration becomes more unstable and so errors in computation add up to result in a basis that has errors propagated through each operation.

In [19]:
p40 = np.random.randint(-5, 5, (41, 41))
res = gram_schmidt(p40, tol=1e-40)
dot_matrix = np.zeros((41, 41))

for i in range(41):
    for j in range(41):
        dot_matrix[i, j] = polynomialdot(p40[i], p40[j])

print("Below is the resulting orthonormal set of polynomials for the randomly generated set of vectors of degree at most 40.")
print(res)
print("Below is the resulting dot product matrix for the randomly generated set of vectors of degree at most 40.")
print(dot_matrix)

Below is the resulting orthonormal set of polynomials for the randomly generated set of vectors of degree at most 40.
[[ 6.59641918e-01  4.94731439e-01 -6.59641918e-01 ...  4.94731439e-01
  -1.64910480e-01  6.59641918e-01]
 [-5.81853989e-01 -4.60219017e-01  2.95911679e-01 ...  3.02293809e-01
   4.07577281e-01  2.75972941e-01]
 [-2.07787618e-01  1.85841617e+00 -3.75304663e+00 ... -4.51900801e+00
  -3.04777384e+00 -2.84498388e+00]
 ...
 [ 5.09979402e+00 -6.23125151e+02  1.85612491e+04 ...  1.68302487e+07
  -1.37467850e+08  5.84437507e+07]
 [-3.67228969e+00  4.47982330e+02 -1.33098951e+04 ... -1.18625774e+07
   9.67935827e+07 -4.10959348e+07]
 [ 3.91493749e+00 -4.80717410e+02  1.43867825e+04 ...  1.11113492e+07
  -9.87853667e+07  4.21759655e+07]]
Below is the resulting dot product matrix for the randomly generated set of vectors of degree at most 40.
[[ 36.77083487  10.15421913  14.63075755 ...  13.52147798  30.51709513
    1.93852801]
 [ 10.15421913 112.87830732 100.73511699 ...   1.3847