In [1]:
import numpy as np

# Problem 1

In [28]:
np.random.seed(1)

d = 10
n = 10

v = np.random.randn(d, n)
u = np.random.randn(d, 1)

norm_vals = np.zeros(n)

for k in range(n):
    proj = np.zeros(d)
    for i in range(k):
        proj += (v[i].dot(u.T[0]))/(v[i].dot(v[i]))*v[i]
    norm_vals[k] = np.linalg.norm(u-proj, ord=2)

for i, val in enumerate(norm_vals):
    print(str(i+1) + ": " + str(val))

1: 7.051177983951208
2: 7.045675966865446
3: 7.066540742601932
4: 7.224218024063238
5: 7.53831764025483
6: 7.713878956062961
7: 8.66319880866332
8: 8.678800230944349
9: 8.894730083306841
10: 9.467587861627797


# Problem 4
## Part a)

In [17]:
A = -5*np.random.random((2, 2))+5*np.random.random((2, 2))
B = A.copy()
B[0, 0] = 0

A_norm = np.linalg.norm(A, ord=2)
B_norm = np.linalg.norm(B, ord=2)

if A_norm < B_norm:
    print(A)
else:
    print("Fail")

[[-0.49209018  1.51475188]
 [-3.06519525 -3.04412915]]


# Problem 5
## Part b)

In [29]:
n = 50
r = 1-(1/1000)
v = np.array([r**i for i in range(n)])
v = np.reshape(v, (-1, 1))
A = v.dot(v.T)
A[0, 0] = 0
A

array([[0.        , 0.999     , 0.998001  , ..., 0.95406496, 0.9531109 ,
        0.95215779],
       [0.999     , 0.998001  , 0.997003  , ..., 0.9531109 , 0.95215779,
        0.95120563],
       [0.998001  , 0.997003  , 0.996006  , ..., 0.95215779, 0.95120563,
        0.95025442],
       ...,
       [0.95406496, 0.9531109 , 0.95215779, ..., 0.91023995, 0.90932971,
        0.90842038],
       [0.9531109 , 0.95215779, 0.95120563, ..., 0.90932971, 0.90842038,
        0.90751196],
       [0.95215779, 0.95120563, 0.95025442, ..., 0.90842038, 0.90751196,
        0.90660445]])

In [30]:
N = int(1e6)

best_lb = 0
for i in range(N):
    v = np.random.random((50,))
    lb = np.linalg.norm(np.matmul(A, v), ord=2)/np.linalg.norm(v, ord=2)
    
    if lb > best_lb:
        best_lb = lb

print("Best bound: " + str(best_lb))


Best bound: 45.54763411107522


# Problem 7
## Part a)

In [31]:
A4 = np.array([[-2,1,0,1], [1,-2,1,0], [0,1,-2,1], [1,0,1,-2]])
A4_norm = np.linalg.norm(A4, ord=2)
print("Norm of A_4: " + str(A4_norm))

Norm of A_4: 4.0


In [32]:
A5 = np.array([[-2,1,0,0,1], [1,-2,1,0,0], [0,1,-2,1,0], [0,0,1,-2,1], [1,0,0,1,-2]])
A5_norm = np.linalg.norm(A5, ord=2)
print("Norm of A_5: " + str(A5_norm))

Norm of A_5: 3.6180339887498945


In [33]:
A6 = np.array([[-2,1,0,0,0,1], [1,-2,1,0,0,0], [0,1,-2,1,0,0], [0,0,1,-2,1,0], [0,0,0,1,-2,1], [1,0,0,0,1,-2]])
A6_norm = np.linalg.norm(A6, ord=2)
print("Norm of A_6: " + str(A6_norm))

Norm of A_6: 3.999999999999999


# Problem 9
## Part f)

In [34]:
F = np.array([[1,1,-1],[0,1,1],[1,0,1]])
V, D, UT = np.linalg.svd(F)

print("V = " + str(V))
print("D = " + str(D))
print("U^T = " + str(UT))

V = [[-5.77350269e-01 -8.16496581e-01  1.11022302e-16]
 [ 5.77350269e-01 -4.08248290e-01 -7.07106781e-01]
 [ 5.77350269e-01 -4.08248290e-01  7.07106781e-01]]
D = [1.73205081 1.73205081 1.        ]
U^T = [[ 0.00000000e+00 -4.71027738e-16  1.00000000e+00]
 [-7.07106781e-01 -7.07106781e-01 -3.33066907e-16]
 [ 7.07106781e-01 -7.07106781e-01 -3.33066907e-16]]


## Part g)

In [35]:
G = np.array([[1,-2,0],[0,1,1]])
V, D, UT = np.linalg.svd(G)

print("V = " + str(V))
print("D = " + str(D))
print("U^T = " + str(UT))

V = [[-0.89442719  0.4472136 ]
 [ 0.4472136   0.89442719]]
D = [2.44948974 1.        ]
U^T = [[-3.65148372e-01  9.12870929e-01  1.82574186e-01]
 [ 4.47213595e-01  1.11022302e-16  8.94427191e-01]
 [-8.16496581e-01 -4.08248290e-01  4.08248290e-01]]


In [49]:
F = np.array([[1,-1,0],[0,1,1]])
F_norm = np.linalg.norm(F, ord=2)
F_norm

1.7320508075688774